# Generated by Django 5.2.6 on 2025-09-05 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Request', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='supply/')),
                ('total_amount', models.DecimalField(decimal_places=0, help_text='총액(원). 나눔이면 0원 가능', max_digits=12)),
                ('max_participants', models.PositiveIntegerField(help_text='최대 인원(총원). 1 이상')),
                ('apply_deadline', models.DateTimeField(help_text='신청 마감 시각')),
                ('execute_time', models.DateTimeField(help_text='시행(실행) 시각')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FILLED', 'Filled'), ('EXECUTED', 'Executed'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, help_text='원본 요청글(FK). 선택. 카드 표시는 이 FK로 조회해서 렌더링.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies', to='Request.task')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_comment', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='supply.supplypost')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('unit_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('content', models.TextField(blank=True, help_text='신청 시 남긴 요청사항/메모')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_joins', to=settings.AUTH_USER_MODEL)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joins', to='supply.supplypost')),
            ],
            options={
                'unique_together': {('supply', 'user')},
            },
        ),
    ]
