# Generated by Django 5.2.6 on 2025-09-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_account',
            field=models.CharField(default=0, help_text='00000000000000', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='김신촌', help_text='이름(실명)', max_length=10),
            preserve_default=False,
        ),
    ]
